name: smartresponse4
description: Smart Response Emergency Communication Application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  background_locator: ^1.2.2+1 #MIT
  cloud_firestore: ^0.14.1+1 # 12.9+4 old ver bsd https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/LICENSE
  cupertino_icons: ^0.1.2 #mit license
  firebase_auth: ^0.18.1+1 #old version is 0.16.1 bsd license https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/LICENSE
  firebase_core: ^0.5.0 #bsd https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_core/firebase_core/LICENSE
  firebase_messaging: ^7.0.0 #bsd https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/LICENSE
  flutter_launcher_icons: ^0.8.0 #MIT license
  flutter_local_notifications: ^1.4.4 # BSD https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/LICENSE
  flutter_spinkit: ^4.1.2+1 #MIT
  fluttertoast: ^7.1.2 #MIT https://pub.dev/packages/fluttertoast
  geolocator: ^5.3.2+2 #mit license
  google_maps_flutter: ^0.5.30 # bsd  https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter/LICENSE
  location: ^2.3.5 #MIT
  location_permissions: ^3.0.0 #MIT
  maps_launcher: ^1.2.2+1 #MIT
  path_provider: ^1.6.5 # bsd https://github.com/flutter/plugins/blob/master/packages/path_provider/path_provider/LICENSE
  permission: ^0.1.7 # https://pub.dev/packages/permission   - license file is empty
  provider: ^4.1.0 # MIT //was 3.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/sricon-full.png"

# some packages that were used in the past that are not currently used
# google_maps_flutter: ^0.5.21+15
#  firebase_core: ^0.4.5
#  firebase_messaging: ^6.0.16

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
